# Generated by Codex on 2026-02-10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def forward_copy_categories_to_departments(apps, schema_editor):
    Category = apps.get_model("vault", "Category")
    Department = apps.get_model("vault", "Department")
    Service = apps.get_model("vault", "Service")
    User = apps.get_model("vault", "User")

    category_to_department_id = {}
    for category in Category.objects.all().order_by("id"):
        department = Department.objects.create(
            name=category.name,
            sort_order=category.sort_order,
            is_active=category.is_active,
        )
        category_to_department_id[category.id] = department.id

    for service in Service.objects.all().only("id", "category_id"):
        service.department_id = category_to_department_id.get(service.category_id)
        service.save(update_fields=["department"])

    User.objects.filter(role="admin").update(role="head")


class Migration(migrations.Migration):

    dependencies = [
        ("vault", "0002_serviceaccess"),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=120, unique=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.AddField(
            model_name="user",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="vault.department",
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="services",
                to="vault.department",
            ),
        ),
        migrations.CreateModel(
            name="DepartmentShare",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("expires_at", models.DateTimeField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "department",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="shares", to="vault.department"),
                ),
                (
                    "grantor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="granted_department_shares",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "grantee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_department_shares",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("department", "grantor", "grantee")},
            },
        ),
        migrations.RunPython(forward_copy_categories_to_departments, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="service",
            name="category",
        ),
        migrations.DeleteModel(
            name="Category",
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("head", "Department Head"), ("employee", "Employee")],
                default="employee",
                max_length=16,
            ),
        ),
    ]
