# Generated by Django 4.2.28 on 2026-06-02 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0008_remove_oauth_client_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='iin',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
    ]
