# Generated by Django 4.2.28 on 2026-06-02 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0009_user_iin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='credential',
            options={'ordering': ['-updated_at', 'service__name']},
        ),
        migrations.AlterModelOptions(
            name='serviceaccess',
            options={'ordering': ['-updated_at', 'service__name']},
        ),
    ]
