# Generated by Django 4.2.28 on 2026-06-03 05:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def normalize_empty_user_emails(apps, schema_editor):
    User = apps.get_model("vault", "User")
    User.objects.filter(email="").update(email=None)


class Migration(migrations.Migration):

    dependencies = [
        ("vault", "0010_alter_credential_options_alter_serviceaccess_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.RunPython(normalize_empty_user_emails, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.CreateModel(
            name="EmailVerificationChallenge",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "purpose",
                    models.CharField(
                        choices=[("registration", "Registration"), ("password_reset", "Password reset")],
                        max_length=32,
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("code_digest", models.CharField(max_length=64)),
                ("salt", models.CharField(max_length=64)),
                ("expires_at", models.DateTimeField()),
                ("consumed_at", models.DateTimeField(blank=True, null=True)),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("max_attempts", models.PositiveSmallIntegerField(default=5)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, default="", max_length=512)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_verification_challenges",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
